name: CI
on: 
  push:
    branches:
      - main
      - master
  pull_request:
jobs:

  build:
    name: build
    runs-on: windows-latest
    steps:

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
        id: go

      - name: Check out code
        uses: actions/checkout@v1
      
      - name: Build
        run: make buildwin
